### ISSUE TITLE
Starting Homebridge

### ISSUE THREAD

**Issue by QuinnDD** [KraigM/homebridge-gpio-garagedoor#1]
I have installed the plugin successfully, the config.json file is correct and adapted!
When I start the homebridge with the commands:

Sudo systemctl daemon-reload
Sudo systemctl enable homebridge
Sudo systemctl start homebridge 
Sudo systemctl status homebridge 

I see the homebridge isn't working. I can't figure it out why he won't work. 
Can you guys help me please.

Im trying to control a PIFACE 2 by homebridge with this plugin. Is this even possible ?

**Comment by KraigM** [comment]
This is really a [Homebridge](https://github.com/nfarina/homebridge) question, not specific to this plugin.  Please writeup and issue there.  Though I would just try calling `homebridge` and make sure it is working when you start it manually.  That might give you a proper error message.
