### ISSUE TITLE
Start up with relay LOW

### ISSUE THREAD

**Issue by didl001** [KraigM/homebridge-gpio-garagedoor#13]
Is there an opinion to start up with the DoorSwitchPin pulled LOW?
Then get the Pin HIGH to start the gargedoor and back LOW.

The issue now is, when you reboot the Raspberry or maybe the Powerunit of the Rasp or Relayboard goes down, the Door would open by Fault.

**Comment by SmittyK** [comment]
I threw the kitchen sink at a low driven relay trying to get around this issue. Replaced it with an inexpensive high driven relay to get around it. see this thread: https://github.com/KraigM/homebridge-gpio-garagedoor/issues/2

**Comment by didl001** [comment]
Can you get us a link to the relay please!

**Comment by SmittyK** [comment]
http://www.ebay.com/itm/201658287598?_trksid=p2057872.m2749.l2649&ssPageName=STRK%3AMEBIDX%3AIT

**Comment by didl001** [comment]
Thanks for share your info! Ordert a similar one in Germany, cause i´m from Austria

**Comment by hitme666** [comment]
Still not fixing the issue ;)

I could use a fix fot it also.

**Comment by didl001** [comment]
@hitme666

You tried the high trigger relay and the issue is the same?

**Comment by didl001** [comment]
Issue is fixed with the High driven Relay! Nothing on the Code have to be Changed! Even on a Reboot or if the Raspberry get Powerless the Garage-door kept close!

A big Thanks on @SmittyK for this Fix and also on @KraigM for this nice Application
